# Generated by Django 4.0.5 on 2022-07-19 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef_menage',
            fields=[
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('annee_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(default='abidjan', max_length=100)),
                ('nationalite', models.CharField(default='ivoirienne', max_length=100)),
                ('numero_cni', models.CharField(max_length=100)),
                ('sexes', models.CharField(choices=[('M', 'Maxculin'), ('F', 'Feminin')], max_length=1)),
                ('ethnie', models.CharField(max_length=100)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_mariage', models.CharField(choices=[('M', 'Monogamie'), ('P', 'Polygamie')], max_length=100)),
                ('immigre', models.BooleanField(default=False)),
                ('agentr', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('A', 'Abidjan'), ('B', 'Bas_Sassandra'), ('C', 'Comoe'), ('D', 'Denguele'), ('G', 'Goh_Djiboua'), ('L', 'Lacs'), ('La', 'Lagunes'), ('M', 'Montagnes'), ('SM', 'Sassandra_Marahoue'), ('Sa', 'Savanes'), ('Va', 'Vallee_du_Bandama'), ('W', 'Woroba'), ('Y', 'Yamoussoukro'), ('Za', 'Zanzan')], max_length=100)),
                ('region', models.CharField(choices=[('A', 'Abidjan'), ('AT', 'Agneby_tiassa'), ('Ba', 'Bafing'), ('Ba', 'Bagoue'), ('Be', 'Belier'), ('B', 'Bere'), ('Bo', 'Bounkani'), ('Ca', 'Cavally'), ('Fo', 'Folon'), ('Gb', 'Gbeke'), ('Gbo', 'Gbokle'), ('Go', 'Goh'), ('Gu', 'Guemon'), ('In', 'Indenie_djuablin'), ('Ka', 'Kabadougou'), ('Na', 'Nawa'), ('Lo', 'Loh_Djiboua'), ('If', ' Iffou'), ('Mo', 'Moronou'), ('Nz', 'Nzi'), ('LM', 'La_Me'), ('To', 'Tonkpi'), ('Hs', 'Haut_Sassandra'), ('Mr', 'Marahoué'), ('Po', 'Poro'), ('Tc', 'Tchologo'), ('Ha', 'Hambol'), ('Go', 'Gontougou'), ('Sp', 'San_pedro'), ('Sc', 'Sud_Comoe'), ('Wo', 'Worodougou')], max_length=100)),
                ('departement', models.CharField(max_length=100)),
                ('sous_prefecture', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('milieu_r', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion', models.CharField(choices=[('C', 'Catholique'), ('M', 'Méthodique'), ('E', 'Evangélique'), ('Ce', 'Céleste'), ('H', 'Harriste'), ('Au', 'AutreRC'), ('Mu', 'Mulsuman'), ('An', 'Animiste'), ('Au', 'AutreR'), ('S', 'Sans_Religion')], max_length=100)),
                ('handicap', models.CharField(choices=[('S', 'Sans_Handicap'), ('Nv', 'Non_voyant'), ('So', 'Sourd'), ('Mu', 'Muet'), ('Be', 'Begue'), ('Al', 'Albinos'), ('Hms', 'Handicap_membre_superieurs'), ('Hmi', 'Handicap_membre_inferieurs'), ('Hp', 'Handicap_physiques'), ('Au', 'Autre_handicap')], max_length=100)),
                ('survie_de_mere', models.CharField(choices=[('Vm', 'Vie_Ménage'), ('Hm', 'Hors_Ménage'), ('D', 'Décédé'), ('N', 'RAS')], max_length=100)),
                ('survie_de_pere', models.CharField(choices=[('Vm', 'Vie_Ménage'), ('Hm', 'Hors_Ménage'), ('D', 'Décédé'), ('N', 'RAS')], max_length=100)),
                ('alphabetisation', models.BooleanField(default=False)),
                ('niveau_instruction', models.CharField(max_length=100)),
                ('status_occupation', models.CharField(max_length=100)),
                ('occupation_actuelle', models.CharField(max_length=100)),
                ('situation_occupation', models.CharField(max_length=100)),
                ('branche_activite', models.CharField(max_length=100)),
                ('situation_matrimoniale', models.CharField(max_length=100)),
                ('nombre_enfant', models.IntegerField(default=0)),
                ('nombre_enfant_v', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.chef_menage')),
            ],
            options={
                'ordering': ['parent'],
            },
        ),
        migrations.CreateModel(
            name='Migrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deplace', models.BooleanField()),
                ('annee_deplace', models.DateField()),
                ('lieu_residence_a', models.CharField(max_length=100)),
                ('intention_ret', models.BooleanField()),
                ('parentm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.chef_menage')),
            ],
            options={
                'ordering': ['parentm'],
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyen_deplacement', models.CharField(max_length=100)),
                ('equipement_electr', models.CharField(max_length=100)),
                ('equipement_audio', models.CharField(max_length=100)),
                ('statut_occupation', models.CharField(max_length=100)),
                ('parente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.chef_menage')),
            ],
            options={
                'ordering': ['parente'],
            },
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('annee_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(default='abidjan', max_length=100)),
                ('nationalite', models.CharField(default='ivoirienne', max_length=100)),
                ('numero_cni', models.CharField(max_length=100)),
                ('sexes', models.CharField(choices=[('M', 'Maxculin'), ('F', 'Feminin')], max_length=1)),
                ('ethnie', models.CharField(max_length=100)),
                ('ecolier', models.CharField(blank=True, default='oui', max_length=100)),
                ('id1', models.BigAutoField(primary_key=True, serialize=False)),
                ('agentr', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parentf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.chef_menage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexesd', models.CharField(choices=[('M', 'Maxculin'), ('F', 'Feminin')], max_length=1)),
                ('date_depart', models.DateField(null=True)),
                ('motif', models.CharField(max_length=100)),
                ('age_depart', models.PositiveBigIntegerField()),
                ('parentd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.chef_menage')),
            ],
            options={
                'ordering': ['parentd'],
            },
        ),
        migrations.CreateModel(
            name='Deces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexesd', models.CharField(choices=[('M', 'Maxculin'), ('F', 'Feminin')], max_length=1)),
                ('age_deces', models.PositiveBigIntegerField()),
                ('nom_decede', models.CharField(max_length=100)),
                ('prenom_decede', models.CharField(max_length=100)),
                ('annee_deces', models.DateField()),
                ('parentd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.chef_menage')),
            ],
            options={
                'ordering': ['parentd'],
            },
        ),
        migrations.CreateModel(
            name='Conjoint',
            fields=[
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('annee_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(default='abidjan', max_length=100)),
                ('nationalite', models.CharField(default='ivoirienne', max_length=100)),
                ('numero_cni', models.CharField(max_length=100)),
                ('sexes', models.CharField(choices=[('M', 'Maxculin'), ('F', 'Feminin')], max_length=1)),
                ('ethnie', models.CharField(max_length=100)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('niveau_etude', models.CharField(blank=True, default='master', max_length=100)),
                ('occupation', models.CharField(blank=True, default='Informaticien', max_length=100)),
                ('agentr', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.chef_menage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commodite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_piece', models.CharField(max_length=100)),
                ('nombre_piece_dormir', models.CharField(max_length=100)),
                ('nature_mur', models.CharField(max_length=100)),
                ('nature_toit', models.CharField(max_length=100)),
                ('nature_sol', models.CharField(max_length=100)),
                ('lieu_aisance', models.CharField(max_length=100)),
                ('alimentation_eau', models.CharField(max_length=100)),
                ('temps_acces_eau', models.CharField(max_length=100)),
                ('eclairage', models.CharField(max_length=100)),
                ('cuisson', models.CharField(max_length=100)),
                ('evacuation_ordure', models.CharField(max_length=100)),
                ('evacuation_eau', models.CharField(max_length=100)),
                ('loyer', models.CharField(max_length=100)),
                ('parentc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.chef_menage')),
            ],
            options={
                'ordering': ['parentc'],
            },
        ),
        migrations.CreateModel(
            name='Affecter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('agentr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('localite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.localite')),
            ],
        ),
    ]
